server:
  port: 8090

spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "taxii"

camunda:
  bpm:
    admin-user:
      id: "admin"
      password: "admin"
      firstName: "Admin"

#Camunda BPM Engine Core Path:
spring.jersey.application-path: "/bpm-rest"

taxii:
  tenant:
    id: "tenant123"
    slug: "mytenant"
    title: "administration tenant1"
    description: "The admin1 tenant for overall management of the taxii server"
#    tenant_path_pattern:

  discovery:
    title: "My default Discovery"
    description: "The default discovery"

  user:
    username: "admin1"
    password: "admin1"

  basic-auth:
    enabled: "true"


