server:
  port: 8090

spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "taxii"

camunda:
  bpm:
    admin-user:
      id: "admin"
      password: "admin"
      firstName: "Admin"

taxii:
  tenant:
    id: "myId"
    slug: "admin1"
    title: "administration tenant1"
    description: "The admin1 tenant for overall management of the taxii server"

  discovery:
    title: "My default Discovery"
    description: "The default discovery"

  user:
    username: "admin1"
    password: "admin1"

  basic-auth:
    enabled: "false"


