server:
  port: 8090

spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
#      username: ""
#      password: ""

  datasource:
    url: jdbc:h2:~/camunda;DB_CLOSE_ON_EXIT=false;AUTO_SERVER=TRUE;
    username: sa
    password: ""

camunda:
  bpm:
    process-engine-name: taxii
    admin-user:
      id: "taxii-admin"
      password: "taxii-admin"
      firstName: "Taxii"
      lastName: "Admin"

taxii:
  tenant:
    id: "tenant123"
    slug: "mytenant"
    title: "administration tenant1"
    description: "The admin1 tenant for overall management of the taxii server"
#    tenant_path_pattern:

  discovery:
    title: "My default Discovery"
    description: "The default discovery"

  user:
    username: "admin1"
    password: "admin1"

  basic-auth:
    enabled: "true"


